# =============================================================================
# Captain S3 one-click sync, Terraform equivalent of the CloudFormation template
# in ../cloudformation/captain-s3-sync.yaml. Same three things, same
# self-verifying design, all inside the CUSTOMER'S AWS account:
#
#   1. Event wiring: an SNS topic fed by the bucket's ObjectCreated/ObjectRemoved
#      events (attached additively so existing bucket hooks are preserved).
#   2. A read-only cross-account IAM role Captain assumes with the external id
#      (no long-lived keys), scoped to this bucket (and to the prefix / KMS key
#      when supplied).
#   3. A self-verifying enroll Lambda that registers the topic with the real
#      Captain API: POST {captain_api_base}/v2/syncs/{sync_id}/webhooks with
#      "Authorization: Bearer {captain_api_key}" and body
#      {"sns_topic_arn": "<the topic this module just created>"}. Captain
#      subscribes to the topic and returns 2xx JSON with subscribe_url (the
#      per-sync ingest URL it minted), secret_set, and instructions. A 2xx
#      with a subscribe_url IS successful enrollment, and the
#      aws_lambda_invocation postcondition asserts exactly that
#      (verified == true), so `terraform apply` only succeeds if Captain
#      accepted the registration.
#
# NAMING: date-based template version (2026-08-13), Stripe-style deployment id
# (dep_<token>) generated by random_string. No bare UUIDs.
# =============================================================================

provider "aws" {
  region = var.aws_region
}

data "aws_caller_identity" "current" {}
data "aws_partition" "current" {}

locals {
  template_version = "2026-08-13"
  # Per-sync notification config id so two Captain syncs on ONE bucket do not
  # collide (S3 requires notification config ids to be unique within a bucket).
  notification_config_id = "captain-${var.sync_id}"
  deployment_id          = "dep_${random_string.deployment.result}"
}

# Stripe-style deployment id (dep_<token>), stable across applies via state.
resource "random_string" "deployment" {
  length  = 24
  special = false
  upper   = true
  lower   = true
  numeric = true
}

# =============================================================================
# 1. EVENT WIRING: SNS topic + topic policy + additive bucket notification
# =============================================================================

resource "aws_sns_topic" "captain" {
  name         = "captain-s3-sync-${var.sync_id}"
  display_name = "Captain S3 sync for ${var.bucket_name}"

  tags = {
    "captain:sync-id"    = var.sync_id
    "captain:managed-by" = "terraform"
  }
}

# (a) let THIS bucket publish (SourceArn + SourceAccount pin it so no other
# account's bucket can publish), and (b) let Captain's account subscribe its
# endpoint to the topic so Captain can complete the subscription at enrollment.
data "aws_iam_policy_document" "topic" {
  statement {
    sid       = "AllowThisBucketToPublish"
    effect    = "Allow"
    actions   = ["SNS:Publish"]
    resources = [aws_sns_topic.captain.arn]

    principals {
      type        = "Service"
      identifiers = ["s3.amazonaws.com"]
    }
    condition {
      test     = "ArnLike"
      variable = "aws:SourceArn"
      values   = ["arn:${data.aws_partition.current.partition}:s3:::${var.bucket_name}"]
    }
    condition {
      test     = "StringEquals"
      variable = "aws:SourceAccount"
      values   = [data.aws_caller_identity.current.account_id]
    }
  }

  statement {
    sid       = "AllowCaptainToSubscribe"
    effect    = "Allow"
    actions   = ["SNS:Subscribe", "SNS:GetTopicAttributes"]
    resources = [aws_sns_topic.captain.arn]

    principals {
      type        = "AWS"
      identifiers = ["arn:${data.aws_partition.current.partition}:iam::${var.captain_account_id}:root"]
    }
  }
}

resource "aws_sns_topic_policy" "captain" {
  arn    = aws_sns_topic.captain.arn
  policy = data.aws_iam_policy_document.topic.json
}

# ---- Additive bucket notification via the setnotif Lambda -------------------
# See functions/setnotif.py for why this is a Lambda and not the authoritative
# aws_s3_bucket_notification resource (that one would clobber existing hooks).

resource "aws_cloudwatch_log_group" "setnotif" {
  name              = "/aws/lambda/captain-s3-setnotif-${var.sync_id}"
  retention_in_days = var.log_retention_days
}

data "aws_iam_policy_document" "setnotif_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "setnotif" {
  name               = "captain-s3-setnotif-${var.sync_id}"
  assume_role_policy = data.aws_iam_policy_document.setnotif_assume.json
}

resource "aws_iam_role_policy_attachment" "setnotif_basic" {
  role       = aws_iam_role.setnotif.name
  policy_arn = "arn:${data.aws_partition.current.partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

data "aws_iam_policy_document" "setnotif" {
  statement {
    effect    = "Allow"
    actions   = ["s3:GetBucketNotification", "s3:PutBucketNotification"]
    resources = ["arn:${data.aws_partition.current.partition}:s3:::${var.bucket_name}"]
  }
}

resource "aws_iam_role_policy" "setnotif" {
  name   = "manage-this-bucket-notification"
  role   = aws_iam_role.setnotif.id
  policy = data.aws_iam_policy_document.setnotif.json
}

data "archive_file" "setnotif" {
  type        = "zip"
  source_file = "${path.module}/functions/setnotif.py"
  output_path = "${path.module}/.build/setnotif.zip"
}

resource "aws_lambda_function" "setnotif" {
  function_name    = "captain-s3-setnotif-${var.sync_id}"
  runtime          = "python3.12"
  handler          = "setnotif.handler"
  timeout          = 120
  role             = aws_iam_role.setnotif.arn
  filename         = data.archive_file.setnotif.output_path
  source_code_hash = data.archive_file.setnotif.output_base64sha256

  environment {
    variables = {
      CAPTAIN_DEBUG = var.debug_logging
    }
  }

  depends_on = [
    aws_cloudwatch_log_group.setnotif,
    aws_iam_role_policy_attachment.setnotif_basic,
    aws_iam_role_policy.setnotif,
  ]
}

# Invoke on create/update/destroy (lifecycle_scope = CRUD). The function does an
# additive read-merge-write and, on destroy, removes only our config. S3 rejects
# PutBucketNotification until the topic already grants sns:Publish, so this
# depends on the topic policy.
resource "aws_lambda_invocation" "setnotif" {
  function_name   = aws_lambda_function.setnotif.function_name
  lifecycle_scope = "CRUD"

  input = jsonencode({
    BucketName   = var.bucket_name
    TopicArn     = aws_sns_topic.captain.arn
    ConfigId     = local.notification_config_id
    ObjectPrefix = var.object_prefix
  })

  # NO `triggers` block here on purpose. A previous fix used
  # `triggers = { redeploy_at = timestamp() }` to force a re-invoke on every
  # apply, but `triggers` is a force-REPLACE argument on aws_lambda_invocation:
  # any change to it (and timestamp() changes on every plan) destroys and
  # recreates this resource, which for setnotif means the real S3 bucket
  # notification config gets REMOVED and RE-ADDED, with a real window where the
  # bucket has no hook, on every single terraform apply, including applies
  # where nothing about this sync changed. Live-confirmed via CloudWatch: two
  # back-to-back applies with no input changes still produced two setnotif
  # invocations and two PutBucketNotificationConfiguration calls. Removed.
  #
  # Without a trigger, this resource re-invokes the Lambda only when `input`
  # actually changes (a real bucket/topic/prefix change), which is correct and
  # non-destructive. The trade-off: if an apply's postcondition below fails,
  # the failing `result` is cached in state, and a later `terraform apply`
  # with IDENTICAL input is a no-op that will not call the Lambda again --
  # see the loud, explicit retry instruction in the postcondition error below
  # and in README.md "Retrying a failed apply".
  depends_on = [aws_sns_topic_policy.captain]

  lifecycle {
    postcondition {
      condition = try(jsondecode(self.result).ok, false) == true
      error_message = join(" ", [
        "Failed to set bucket notification on ${var.bucket_name}.",
        "Lambda returned: ${self.result}.",
        "A plain `terraform apply` will NOT retry this on its own if nothing",
        "else changed (the cached failure is what you are seeing now). Once",
        "you have fixed the underlying cause, force a real retry with:",
        "terraform apply -replace=aws_lambda_invocation.setnotif",
      ])
    }
  }
}

# =============================================================================
# 2. CROSS-ACCOUNT READ ROLE (assume_role path, no long-lived keys)
# =============================================================================

data "aws_iam_policy_document" "read_assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type        = "AWS"
      identifiers = ["arn:${data.aws_partition.current.partition}:iam::${var.captain_account_id}:root"]
    }
    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"
      values   = [var.external_id]
    }
  }
}

data "aws_iam_policy_document" "read" {
  statement {
    sid       = "ListThisBucket"
    effect    = "Allow"
    actions   = ["s3:ListBucket"]
    resources = ["arn:${data.aws_partition.current.partition}:s3:::${var.bucket_name}"]

    # When a prefix is set, listing is confined to it. Captain lists with the
    # prefix on a prefixed sync, so this stays functional while keeping key
    # names outside the prefix invisible.
    dynamic "condition" {
      for_each = var.object_prefix != "" ? [1] : []
      content {
        test     = "StringLike"
        variable = "s3:prefix"
        values   = ["${var.object_prefix}*"]
      }
    }
  }

  statement {
    sid     = "GetObjectsInThisBucket"
    effect  = "Allow"
    actions = ["s3:GetObject"]
    resources = [
      var.object_prefix != ""
      ? "arn:${data.aws_partition.current.partition}:s3:::${var.bucket_name}/${var.object_prefix}*"
      : "arn:${data.aws_partition.current.partition}:s3:::${var.bucket_name}/*"
    ]
  }

  # Only present for SSE-KMS buckets: decrypt scoped to the one key.
  dynamic "statement" {
    for_each = var.kms_key_arn != "" ? [1] : []
    content {
      sid       = "DecryptWithBucketCmk"
      effect    = "Allow"
      actions   = ["kms:Decrypt", "kms:DescribeKey"]
      resources = [var.kms_key_arn]
    }
  }
}

resource "aws_iam_role" "read" {
  name                 = "captain-s3-read-${var.sync_id}"
  description          = "Read-only access to ${var.bucket_name} for Captain sync ${var.sync_id}."
  max_session_duration = 3600
  assume_role_policy   = data.aws_iam_policy_document.read_assume.json

  tags = {
    "captain:sync-id"    = var.sync_id
    "captain:managed-by" = "terraform"
  }
}

resource "aws_iam_role_policy" "read" {
  name   = "read-this-bucket-only"
  role   = aws_iam_role.read.id
  policy = data.aws_iam_policy_document.read.json
}

# =============================================================================
# 3. SELF-VERIFYING ENROLLMENT (apply succeeds only if Captain accepts it)
# =============================================================================

resource "aws_cloudwatch_log_group" "enroll" {
  name              = "/aws/lambda/captain-s3-enroll-${var.sync_id}"
  retention_in_days = var.log_retention_days
}

resource "aws_iam_role" "enroll" {
  name               = "captain-s3-enroll-${var.sync_id}"
  assume_role_policy = data.aws_iam_policy_document.setnotif_assume.json
}

# No extra permissions: this function only makes an outbound HTTPS call to
# Captain and returns its result. It touches no AWS resources.
resource "aws_iam_role_policy_attachment" "enroll_basic" {
  role       = aws_iam_role.enroll.name
  policy_arn = "arn:${data.aws_partition.current.partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

data "archive_file" "enroll" {
  type        = "zip"
  source_file = "${path.module}/functions/enroll.py"
  output_path = "${path.module}/.build/enroll.zip"
}

resource "aws_lambda_function" "enroll" {
  function_name    = "captain-s3-enroll-${var.sync_id}"
  runtime          = "python3.12"
  handler          = "enroll.handler"
  timeout          = 180
  role             = aws_iam_role.enroll.arn
  filename         = data.archive_file.enroll.output_path
  source_code_hash = data.archive_file.enroll.output_base64sha256

  environment {
    variables = {
      CAPTAIN_DEBUG = var.debug_logging
    }
  }

  depends_on = [
    aws_cloudwatch_log_group.enroll,
    aws_iam_role_policy_attachment.enroll_basic,
  ]
}

# Run the enrollment LAST: only register the webhook once the topic, policy,
# notification, and read role all exist, so Captain subscribes to real,
# finished plumbing. The postcondition is the self-verify: apply fails unless
# the Lambda reports verified == true, which it only does on a 2xx from
# Captain carrying a subscribe_url. On destroy (lifecycle_scope CRUD) the
# Lambda runs once more but calls nothing: there is no documented unsubscribe
# endpoint, and none is needed. Destroying the module removes the SNS topic;
# Captain detects the dead event source and reconcile remains the backstop.
resource "aws_lambda_invocation" "enroll" {
  function_name   = aws_lambda_function.enroll.function_name
  lifecycle_scope = "CRUD"

  input = jsonencode({
    CaptainApiBase = var.captain_api_base
    CaptainApiKey  = var.captain_api_key
    SyncId         = var.sync_id
    SnsTopicArn    = aws_sns_topic.captain.arn
    DeploymentId   = local.deployment_id
  })

  # NO `triggers` block here on purpose (see aws_lambda_invocation.setnotif
  # above for the general reasoning): `triggers = { redeploy_at = timestamp() }`
  # forces destroy-then-create on every single apply, so the webhook
  # registration would be re-POSTed to Captain on every unrelated apply, not
  # just retries. Live-confirmed via CloudWatch: two back-to-back applies with
  # no input changes still produced two enroll invocations. Removed.
  #
  # Trade-off (same as setnotif): a failed registration gets cached in state,
  # and a later `terraform apply` with IDENTICAL input will not re-ask Captain
  # on its own. Once the underlying cause is fixed (a corrected sync id, a
  # valid API key), retry with the explicit command named in the postcondition
  # error below, not a bare re-apply.
  depends_on = [
    aws_sns_topic_policy.captain,
    aws_lambda_invocation.setnotif,
    aws_iam_role_policy.read,
  ]

  lifecycle {
    postcondition {
      condition = try(jsondecode(self.result).verified, false) == true
      error_message = join(" ", [
        "Captain did not accept the webhook registration (no 2xx with a",
        "subscribe_url). Lambda returned: ${self.result}.",
        "A plain `terraform apply` will NOT retry this on its own if nothing",
        "else changed (the cached failure is what you are seeing now). Once",
        "the underlying cause is fixed (a corrected sync_id, a valid API key), force",
        "a real retry with: terraform apply -replace=aws_lambda_invocation.enroll",
      ])
    }
  }
}
